### ISSUE TITLE
Developer conventions for all cellfinder projects

### ISSUE THREAD

**Issue by alessandrofelder** [brainglobe/bg-gitbook#4]
Developer conventions are only currently only documented for cellfinder, not for cellfinder-core or cellfinder-napari. Should we have a central place to document developer conventions across all cellfinder projects? Or even across all of BG?

**Comment by adamltyson** [comment]
I’m happy for all the projects I maintain (cellfinder, brainreg and their various add-ons). Cc’ing @vigji and @FedeClaudi about the other projects.

**Comment by vigji** [comment]
I think that defining this is a good idea!

**Comment by alessandrofelder** [comment]
@vigji @FedeClaudi would you be happy with the conventions in #3 ?

**Comment by adamltyson** [comment]
Started here:
https://github.com/brainglobe/.github/pull/2
